services:
  - type: web
    name: playportal-server
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: "*"
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
